esphome:
  name: esphome-MS5837-example
  libraries:
   - "Arduino"
   - "Wire"
   - "SPI"
  includes:
   - MS5837_Component.h

esp32:
  board: node32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a
    
sensor:
  - platform: custom
    lambda: |-
      auto MS5837 = new MS5837_Component(60000, MS5837_MODE_ALTITUDE);
      MS5837->SetUnits(MS5837_UNITS_TEMP_F, MS5837_UNITS_PRESS_INHG, MS5837_UNITS_ALT_FT);
      MS5837->SetOffsets(0, 1.7f);
      MS5837->SetResultsAvgCount(3);
      MS5837->SubscribeToPressureState("sensor.weather_station_pressure", MS5837_UNITS_PRESS_INHG);
      App.register_component(MS5837);
      return {MS5837->temperature_sensor, MS5837->pressure_sensor, MS5837->altitude_sensor};
    sensors:
      - name: "MS5837 Temperature"
        unit_of_measurement: °F
        accuracy_decimals: 1
      - name: "MS5837 Pressure"
        unit_of_measurement: inHg
        accuracy_decimals: 4
      - name: "MS5837 Altitude"
        unit_of_measurement: ft
        accuracy_decimals: 1
